### ISSUE TITLE
lightwalletd stress tests

### ISSUE THREAD

**Issue by braddmiller** [zcash/lightwalletd#178] opened 2020-01-28 17:12 UTC
Conduct stress tests on lightwalletd to provide some performance upper limits for:

- [x] Simultaneous connections
- [x] Request load
Approximate bandwidth usage based on the above load tests. (to approximate running costs) (**EDIT: ** This would be better measured from the wallet making requests, moving off of requirements for this)
- [x] Approximate compute time (to approximate running costs)

**Comment by LarryRuane** [comment] 2020-02-19 18:23
Note that for the time being at least, these do not need to be automated tests, only manual tests. But the procedures should be clearly documented (here) so that the tests may be re-run later (they should probably be run periodically). The results will be published here.

**Comment by LarryRuane** [comment] 2020-02-24 03:55
Results will go here: https://docs.google.com/spreadsheets/d/1vPXFNFFMTOvV5S1okz6bbIeyZ1Wy6QtwdoQmLx2HkxQ/edit#gid=0

**Comment by lindanlee** [comment] 2020-02-27 19:42
Repointed for the new sprint, since some work was done past sprint. 13 > 8.

**Comment by LarryRuane** [comment] 2020-03-04 20:42
That spreadsheet has all the results, I think this ticket can be closed. (Although.... I may do just a little more experimenting so maybe leave it open for a bit longer).

**Comment by LarryRuane** [comment] 2020-03-11 14:51
I ran the following command:
```
time testclient/main -v -concurrency 500000 -iterations 1 -op ping 200000000
```
This says to run 500,000 threads, each submitting a `ping` request to the lwd server, and have the server wait 20 seconds (the units are microseconds... that may be too fine-grain) before returning a response. The response shows that all 500,000 requests were in the server at the same time. All requests completed successfully within about 4 minutes real-time. The lwd server's memory usage increased to about 4 GB, so very roughly 8 KB per pending request, which seems reasonable.

I also tried doubling the load to 1 M requests, and it did not fail, but my system became unresponsive for several minutes; I believe it was swapping / paging (this virtualbox VM is configured with 12 GB of ram), so that's not productive.

Anyone else should be able to reproduce these results using the PR #207 branch (which will be merged to master soon).

**Closed** 2020-03-12 17:46 UTC
Labels: performance, testing
