### ISSUE TITLE
Sometimes GetAddressUtxosStream GRPC call is slow

### ISSUE THREAD

**Issue by Chlup** [zcash/lightwalletd#422] opened 2022-12-16 12:50 UTC
**What is the bug?**
Sometimes `GetAddressUtxosStream` GRPC call is much slower than other time.

**Additional context**
This is the testing script which can be used to reproduce this:
```
#!/bin/zsh

for i in {1..100}; do
    time grpcurl -d '{"addresses":["t1gXqfSSQt6WfpwyuCU3Wi7sSVZ66DYQ3Po"], "startHeight": 1730000}' lightwalletd.electriccoin.co:9067  cash.z.wallet.sdk.rpc.CompactTxStreamer/GetAddressUtxosStream
done
```

This is the example output of the script:
```
$ ./benchmark_fetchutxo.sh
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 3% cpu 0.989 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.03s user 0.02s system 5% cpu 0.924 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.945 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.03s user 0.02s system 0% cpu 10.049 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.03s user 0.02s system 4% cpu 0.926 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 5% cpu 0.858 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.950 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.927 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 5% cpu 0.854 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.871 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.01s system 3% cpu 0.944 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.03s user 0.02s system 5% cpu 0.851 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 5% cpu 0.858 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.851 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.03s user 0.02s system 2% cpu 1.925 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 2% cpu 1.616 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 5% cpu 0.911 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.03s user 0.02s system 5% cpu 0.943 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.03s user 0.02s system 5% cpu 0.901 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.817 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.891 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.896 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.909 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.909 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.03s user 0.02s system 3% cpu 1.244 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 2% cpu 1.590 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.03s user 0.02s system 5% cpu 0.897 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.914 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.866 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.03s user 0.02s system 4% cpu 0.941 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.914 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 5% cpu 0.844 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 5% cpu 0.849 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.869 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 0% cpu 7.975 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.914 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 3% cpu 0.899 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 3% cpu 1.372 total
...
```

Typically this call takes < 1 second. But sometimes it's > 1 seconds. And in two cases it's much more (10 and 7 seconds). These two much slower calls are suspicious.

This can be easily reproduced. Just run mentioned script and sooner or later it happens.

**Comment by LarryRuane** [comment] 2022-12-17 05:35
Thanks for the report! Do you know if these occasional longer delays happen with other gRPCs? Or only with `GetAddressUtxosStream`?

I was reproducing this problem by running your script, but the server seemed to have gone down. Is it working for you?

I ran your script against a locally-running `lightwalletd` and all 100 requests completed in 0.01s or less (elapsed time). So I'm not seeing a problem with that request in particular, locally. Maybe this is a network delay? Maybe @softminus @mdr0id can take a look at our production `lightwalletd` server?

**Comment by Chlup** [comment] 2022-12-19 08:16
We started work on benchmarking od the iOS SDK. And it looks that `GetAddressUtxosStream` is only part of the sync process which is unstable in terms of performance. We didn't spot same behavior for other call.

I can run the script and reproduce it without problems:
```
$ ./benchmark_fetchutxo.sh 
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.03s system 0% cpu 7.260 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 1.019 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 3% cpu 1.077 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 1.037 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 1.031 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 1.042 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.933 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 2% cpu 1.577 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 3% cpu 0.901 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.935 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 1.031 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 3% cpu 1.083 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 1.015 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.908 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.916 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 2% cpu 1.646 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 3% cpu 1.132 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 1% cpu 1.935 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.814 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.826 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.816 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.01s user 0.01s system 3% cpu 0.808 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.01s user 0.01s system 2% cpu 0.805 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 5% cpu 0.817 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.826 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.815 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.01s system 4% cpu 0.806 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.01s system 4% cpu 0.822 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.828 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.01s system 3% cpu 0.815 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 5% cpu 0.836 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 0% cpu 8.071 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.828 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 5% cpu 0.823 total
grpcurl -d  lightwalletd.electriccoin.co:9067   0.02s user 0.02s system 4% cpu 0.811 total
```

**Comment by LarryRuane** [comment] 2022-12-24 16:03
This problem seems to happen with other RPCs, try `GetLightdInfo` (and redirect stdout to `/dev/null`) and see if you get the same delays. These delays are happening in my testing with `GetLightdInfo`. It doesn't look like it's specific to `GetAddressUtxosStream`. Also, I never have delays with any gRPCs to a local `lightwalletd`. So it must be a problem in the networking rather than `lightwalletd`. I'm not sure there's anything we can do about this. Maybe it's just inherent in gRPC.

**Comment by LarryRuane** [comment] 2023-05-27 14:15
I'm closing this because I don't know of anything we can do. Feel free to reopen it if needed, thanks.

**Closed by LarryRuane** 2023-05-27 14:15 UTC
Labels: bug
