### ISSUE TITLE
Crash while running in darkside mode

### ISSUE THREAD

**Issue by Chlup** [zcash/lightwalletd#421] opened 2022-12-06 16:11 UTC
**What is the bug?**
I was running lightwalletd in darkside mode and I experienced crash of the server.

Here is the version:
```{"app":"lightwalletd","buildDate":"2022-09-19","buildUser":"chlup","gitCommit":"ad5ecda5fbb5e12799f926b8cd785d54fdd250c8","level":"info","msg":"Starting gRPC server version v0.4.13-5-gad5ecda on 127.0.0.1:9067","time":"2022-12-06T09:38:13+01:00"}```

And here is the stack trace:
```
{"app":"lightwalletd","level":"info","msg":"Darkside active block height 763137 hash 8e69387ea9a4eff4faced6361bbd8d7bb6c30741990b6473713e6879b6cf1d83 txcount 1","time":"2022-12-06T09:34:59+01:00"}
{"app":"lightwalletd","level":"info","msg":"Darkside active block height 763138 hash 351941317019a49fb1e5d8af181457fa75ac59be6a824d182cb9eb60da67e308 txcount 1","time":"2022-12-06T09:34:59+01:00"}
{"app":"lightwalletd","level":"info","msg":"Darkside active block height 763139 hash 3fbd1f8449dc2942b0aa5287e619270050dbbf4d4462d2b99134978184f66919 txcount 1","time":"2022-12-06T09:34:59+01:00"}
{"app":"lightwalletd","level":"info","msg":"Darkside active block height 763140 hash ddfb9d0ab9aa72ac92e01ebdad206e4d8628ce4449f1c660a046bb185fea3db0 txcount 1","time":"2022-12-06T09:34:59+01:00"}
{"app":"lightwalletd","level":"info","msg":"Darkside active block height 763141 hash 3d858a3cebcd80479fdd18eb5b908f9917d68ff0fc53ffc13a5c7c59b8df0c38 txcount 1","time":"2022-12-06T09:34:59+01:00"}
{"app":"lightwalletd","level":"info","msg":"Darkside active block height 763142 hash 0231d6c8c03e6c838b7f2124d336f1273f85f999c6cf8d73ad323c8e5975203c txcount 1","time":"2022-12-06T09:34:59+01:00"}
{"app":"lightwalletd","level":"info","msg":"Darkside active block height 763143 hash b34b9f6f37e18652bf79bec705b640511dd6979ecc3bf5b486b441f9c2eab37a txcount 1","time":"2022-12-06T09:34:59+01:00"}
{"app":"lightwalletd","level":"info","msg":"Darkside active block height 763144 hash 7644c07fedb082c8118ad40fb915cb714fe1f667626f4433695e73f24790987a txcount 1","time":"2022-12-06T09:34:59+01:00"}
{"app":"lightwalletd","level":"info","msg":"Darkside active block height 763145 hash 4af13f14794a314872d53472508aea3b2a5729f821c0595d4b97ccc7a2029522 txcount 1","time":"2022-12-06T09:34:59+01:00"}
{"app":"lightwalletd","level":"info","msg":"Darkside active block height 763146 hash 9b1eca80d2745c4e5a5027bb25a5ffe43aa94c5c528b12facf18386543acbe77 txcount 1","time":"2022-12-06T09:34:59+01:00"}
{"app":"lightwalletd","level":"info","msg":"Darkside active block height 763147 hash c767c2420205976810e036a2d4a50e050c321eb9f20012c2a5118ddd3eb3e707 txcount 1","time":"2022-12-06T09:34:59+01:00"}
{"app":"lightwalletd","level":"info","msg":"Darkside active block height 763148 hash 0b1ed4c43df7ad1e803edfd4c085f7eff501e48377b663752281e4ef0f94d0ae txcount 1","time":"2022-12-06T09:34:59+01:00"}
{"app":"lightwalletd","level":"info","msg":"Darkside active block height 763149 hash 4e9a3ccf2c1eaf91fe7087358807e26232fcc003f03e431d854c36487e4c81e6 txcount 1","time":"2022-12-06T09:34:59+01:00"}
{"app":"lightwalletd","level":"info","msg":"Darkside active block height 763150 hash a09773a65bd99552c5accf6f63ca9c36da33cd4c9902d1cac404c1ceb4375fd5 txcount 1","time":"2022-12-06T09:34:59+01:00"}
{"app":"lightwalletd","level":"info","msg":"darkside: active blocks from 663150 to 663250, latest presented height 763150","time":"2022-12-06T09:34:59+01:00"}
fatal error: sync: Unlock of unlocked RWMutex

goroutine 136 [running]:
sync.fatal({0x17e105c?, 0xc000127440?})
	/usr/local/go/src/runtime/panic.go:1031 +0x1e
sync.(*RWMutex).Unlock(0x1e2b498)
	/usr/local/go/src/sync/rwmutex.go:209 +0x4a
github.com/zcash/lightwalletd/common.DarksideApplyStaged(0xba50e)
	/Users/chlup/Developing/zcash/lightwalletd/common/darkside.go:263 +0x6a3
github.com/zcash/lightwalletd/frontend.(*DarksideStreamer).ApplyStaged(0xc000127780?, {0x153ad9b?, 0xc005b3f170?}, 0xc005b3f1a0?)
	/Users/chlup/Developing/zcash/lightwalletd/frontend/service.go:726 +0x1d
github.com/zcash/lightwalletd/walletrpc._DarksideStreamer_ApplyStaged_Handler.func1({0x19b3ad8, 0xc005b3f0b0}, {0x17418a0?, 0xc005b3f0e0})
	/Users/chlup/Developing/zcash/lightwalletd/walletrpc/darkside_grpc.pb.go:575 +0x78
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1({0x19b3ad8, 0xc005b3f0b0}, {0x17418a0, 0xc005b3f0e0}, 0xc000127820?, 0xc00c37e540)
	/Users/chlup/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0x87
```

**Additional context**
This happened to me for the first time since September.  And I can reproduce it anymore. My lighwalletd was built from master branch. I was running `AdvancedReOrgTests` test suite from iOS SDK project. This crash happened while `testLongSync` was running.

I am not sure if this is worth of a bug report.

**Comment by LarryRuane** [comment] 2022-12-19 21:33
Thanks for the report. I can't reproduce this problem, and I don't see how it can happen by looking at the code. Can you reproduce it?

>And I can reproduce it anymore

Are you saying that you can't reproduce it? I wasn't sure. 

By any chance, could you try the latest version of the code (5d174f7feb702dc19aec5b09d8be8b3d5b17ce45)? It's not tagged as a release, but I should do that soon. There have been several fixes since 0.4.13, so I'm wondering if this problem may have been fixed.

**Comment by Chlup** [comment] 2022-12-20 10:23
I am not able to reproduce it anymore. And it happened only once. I will fetch the latest code.

**Comment by LarryRuane** [comment] 2022-12-23 20:22
Thanks for trying to reproduce it, I'll close this now but if it happens again, please reopen it.

**Closed by LarryRuane** 2022-12-23 20:22 UTC
Labels: bug
